server:
  port: 8801

spring:
  application:
    name: microservice-stream-provider-service
  rabbitmq:
    host: 192.168.43.240
    port: 5672
    username: admin
    password: admin
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
      bindings: # 服务的整合处理
        output: # 这个名字是一个通道的名称
          destination: studyExchange  # 表示要使用的Exchange 名称定义 如果MQ中没有，则会自动创建 类型为topic
          content-type: application/json
          binder: defaultRabbit
eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
    instance-id: send-8801.com  # 在信息列表时显示主机名称
    prefer-ip-address: true     # 访问的路径变为IP地址









